apiVersion: v1
kind: Namespace
metadata:
  name: theia
---
apiVersion: v1
kind: Service
metadata:
 name: theia
spec:
 ports:
 - port: 8443
   name: https
   protocol: TCP
   targetPort: 7443
 selector:
   app: theia
 type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: theiaide/theia-full
        imagePullPolicy: Always
        name: theia
        ports:
        - containerPort: 8443
          name: https
