apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.18.0 (06a2e56)
    traefik.docker.network: traefik_proxy
    traefik.enable: "true"
    traefik.frontend.rule: Host:flow.docker.localhost
  creationTimestamp: null
  labels:
    io.kompose.service: flow
  name: flow
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flow
    spec:
      containers:
      - env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: node-red-admin-auth
              optional: false
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: node-red-admin-auth
        image: wirelos/flow
        name: flow
        ports:
        - containerPort: 1880
        resources: {}
        #volumeMounts:
        #- mountPath: /data
        #  name: flow-claim0
      restartPolicy: Always
      #volumes:
      #- name: flow-claim0
      #  persistentVolumeClaim:
      #    claimName: flow-claim0
status: {}
