apiVersion: v1
kind: Namespace
metadata:
  name: theia
---
apiVersion: v1
kind: Service
metadata:
 name: theia
spec:
 ports:
 - port: 3000
   name: http
   protocol: TCP
 selector:
   app: theia
 type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: theiaide/theia-full
        imagePullPolicy: Always
        name: theia
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - mountPath: /home/project
          name: theia-workspace-claim0
      restartPolicy: Always
      volumes:
      - name: theia-workspace-claim0
        persistentVolumeClaim:
          claimName: theia-workspace-claim0