apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-workspace-claim0
spec:
#  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi