apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-workspace-claim0
  namespace: theia
spec:
  selector:
    matchLabels:
      app: theia
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi