apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pleroma-db-claim0
  name: pleroma-db-claim0
spec:
  selector:
    matchLabels:
      for_app: pleroma-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
