apiVersion: v1
kind: PersistentVolume
metadata:
  name: pleroma-web-volume
  labels:
    for_app: pleroma-web
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /opt/local-path-provisioner/pvc-pleroma-web-volume
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - citadel
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem